.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
#  APT_CACHE_DIR: "$CI_PROJECT_DIR/.cache/apt"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
  - .cache/pip
  - ptdvenv/
  

stages:
  - build-windows
  - build
  - deploy

build-windows:
  extends:
    - .shared_windows_runners
  stage: build-windows
  script:
    - echo "running scripts in the build job"
    - curl.exe -o Miniconda3-latest-Windows-x86_64.exe https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
    - dir
    - Start-Process ./Miniconda3-latest-Windows-x86_64.exe -Args "/InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniconda3" -wait
    - $env:PATH = "$env:userprofile\Miniconda3\condabin" + $env:PATH
    - conda install conda-build
#    - conda env create -f environment.yml
#    - & cmd /k "activate ptdvenv"
#    - python -c "import generateDS; import tinyobj; import gdecomp; import laspy; import pytools4dart"

conda-build:
  stage: build
  image: conda/miniconda3:latest
  script:
    - ptd=$(pwd)
    - apt-get update -qy
    - apt-get install -y gcc g++ git unzip libgtk2.0-0 libsm6 libxft2 curl
    - curl -u $DART_AUTH $DART_URL -o dart.tar.gz
    - tar -xzf dart.tar.gz
    - dest=$(pwd)/$(ls -d DART_*)
    - cd $dest
    - ./install-text.sh $HOME/DART
    - cd $ptd
    - conda env create -f environment.yml
    - conda init bash
    - source ~/.bashrc
    - conda activate ptdvenv
    - cd pytools4dart/examples
    - python -c 'import pytools4dart as ptd;ptd.configure("~/DART")'
    - python use_case_0.py
    - python use_case_1.py
    - python use_case_2.py
    - python use_case_3.py
    - python use_case_4.py
  only:
    - schedules
    
pip-build:
  stage: build
  image: python:latest
  script:
    - ptd=$(pwd)
    - apt-get update -qy
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv ptdvenv
    - source ptdvenv/bin/activate
    #- mkdir -v $APT_CACHE_DIR
    - apt-get install -y libudunits2-dev libnetcdf-dev libproj-dev libgeos-dev libgdal-dev gfortran libspatialindex-dev libgtk2.0-0 default-jdk # -o dir::cache::archives="$APT_CACHE_DIR"
    - pip install pybind11 pygdal==2.4.0.5 geopandas Cython
    - pip install -r requirements.txt
    - pip install .
    - ptd=$(pwd)
    - cd ../
    - curl -u $DART_AUTH $DART_URL -o dart.tar.gz
    - tar -xzf dart.tar.gz
    - dest=$(pwd)/$(ls -d DART_*)
    - cd $dest
    - ./install-text.sh $HOME/DART
    - cd $ptd
    - cd pytools4dart/examples
    - python -c 'import pytools4dart as ptd;ptd.configure("~/DART")'
    - python use_case_0.py
    - python use_case_1.py
    - python use_case_2.py
    - python use_case_3.py
    - python use_case_4.py
  only:
    - schedules


pages:
  stage: deploy
  image: python:latest
  script:
    - apt-get update -qy
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv ptdvenv
    - source ptdvenv/bin/activate
    #- mkdir -v $APT_CACHE_DIR
    - apt-get install -y libudunits2-dev libnetcdf-dev libproj-dev libgeos-dev libgdal-dev gfortran libspatialindex-dev libgtk2.0-0 # -o dir::cache::archives="$APT_CACHE_DIR"
    - pip install pybind11 pygdal==2.4.0.5 geopandas Cython
    - pip install -r requirements.txt
    - pip install .
    #- mkdir -v $APT_CACHE_DIR
    - pip install portray python-markdown-math
    - portray as_html -c pyproject.toml
    - mv site public
  artifacts:
    paths:
     - public
  only:
   - master

