name: ptdvenv
channels:
  - conda-forge
dependencies:
  - cython
  - gdal
  - geopandas
  - git
  - ipython
  - libspatialindex
  - lmfit
  - lxml
  - matplotlib
  - pip
  - plyfile
  - pybind11
  - pytest
  - rtree
  - scipy
  - pip:
      - git+https://gitlab.com/pytools4dart/generateds.git
      - git+https://gitlab.com/pytools4dart/tinyobj.git
      - git+https://gitlab.com/pytools4dart/gdecomp.git
      - git+https://github.com/floriandeboissieu/laspy.git@patch-1
      - git+https://gitlab.com/pytools4dart/pytools4dart.git
