name: ptdvenv
channels:
  - conda-forge
dependencies:
  # python>=3.7 necessary for sqlite3 backup API used in pytools4dart.dbtools.prospect_db.
  # (see https://stackoverflow.com/questions/59758009/sqlite3-connection-object-has-no-attribute-backup)
  - python>=3.7
  - cython
  - colorama
  - gdal
  - geopandas
  - git
  - ipython
  - laspy>=2
  - libspatialindex
  - lmfit
  - lxml
  - matplotlib
  - numba # for prosail (otherwise numpy is reinstalled for pip version)
  - numpy
  - path>=17
  - pip
  - plyfile
  - psutil # for voxelisation
  - pybind11
  - pyjnius
  - pytest
  - rasterio
  - rtree
  - scipy
  - rioxarray
  - gdecomp
  - trimesh
  - pip:
      # - tinyobjloader==2.0.0rc5
      - git+https://gitlab.com/pytools4dart/generateds.git
      - prosail
      # laszip exist in conda but not with python bindings
      # see https://laspy.readthedocs.io/en/latest/installation.html#conda
      - laszip
      - git+https://gitlab.com/pytools4dart/pytools4dart.git
      # in laspy 2.4.1 there was a format error for return_point_wave_location 
      # that was solved but not passed to conda package...
      # https://github.com/laspy/laspy/commit/9bff50597b2835f1a72af027fda1aa917b20a6d7
      - git+https://github.com/laspy/laspy.git
