name: ptdvenv
channels:
  - conda-forge
dependencies:
  # python>=3.7 necessary for sqlite3 backup API used in pytools4dart.dbtools.prospect_db.
  # (see https://stackoverflow.com/questions/59758009/sqlite3-connection-object-has-no-attribute-backup)
  - python>=3.7
  - cython
  - colorama
  - gdal
  - geopandas
  - git
  - ipython
  - laspy>=2
  - libspatialindex
  - lmfit
  - lxml
  - matplotlib
  - numba # for prosail (otherwise numpy is reinstalled for pip version)
  - numpy
  - path.py
  - pip
  - plyfile
  - psutil # for voxelisation
  - pybind11
  - pyjnius
  - pytest
  - rasterio
  - rtree
  - scipy
  - rioxarray
  - gdecomp
  - laszip
  - trimesh
  - pip:
      # - tinyobjloader==2.0.0rc5
      - git+https://gitlab.com/pytools4dart/generateds.git
      - prosail
      - git+https://gitlab.com/pytools4dart/pytools4dart.git
