name: ptdvenv
channels:
  - conda-forge
dependencies:
  # python>=3.7 necessary for sqlite3 backup API used in pytools4dart.dbtools.prospect_db.
  # (see https://stackoverflow.com/questions/59758009/sqlite3-connection-object-has-no-attribute-backup)
  - python>=3.7
  - cython
  - colorama
  - gdal
  - geopandas
  - git
  - ipython
  - laspy
  - libspatialindex
  - lmfit
  - lxml
  - matplotlib
  - pip
  - plyfile
  - pybind11
  - pyjnius
  - pytest
  - rasterio
  - rtree
  - scipy
  - pip:
      - gdecomp
      - tinyobjloader==2.0.0rc5
      - git+https://gitlab.com/pytools4dart/generateds.git
      - git+https://github.com/jgomezdans/prosail.git
      - git+https://gitlab.com/pytools4dart/pytools4dart.git
